version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "Kafka_Example:1:1,Kafka_Example_json:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      image: mongo:3.2.4
#  mongodbevent:
#    image: mongo:3.2.4
#    container_name: "mongodbsampleevent"
#    ports:
#      - 27017:27017
#    command: --smallfiles
#  mongodbquery:
#    image: mongo:3.2.4
#    container_name: "mongodbsamplequery"
#    ports:
#      - 27018:27017
#    command: --smallfiles
